# Generated by Django 5.0.4 on 2024-04-19 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job_userr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='userr',
            new_name='user',
        ),
    ]
